x-spritebot-service: &spritebot-service
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env.infisical
  command: ['/app/entrypoint.sh']
  restart: unless-stopped
  network_mode: bridge
  init: true
  stop_grace_period: 90s

services:
  spritebot:
    <<: *spritebot-service
    container_name: spritebot

  spritebot-blue:
    <<: *spritebot-service
    container_name: spritebot-blue
    profiles: ['bluegreen']
    environment:
      SPRITEBOT_INSTANCE_MODE: standby
      SPRITEBOT_INSTANCE_ID: spritebot-blue

  spritebot-green:
    <<: *spritebot-service
    container_name: spritebot-green
    profiles: ['bluegreen']
    environment:
      SPRITEBOT_INSTANCE_MODE: standby
      SPRITEBOT_INSTANCE_ID: spritebot-green
