services:
  spritebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spritebot
    env_file:
      - .env.infisical
    command: ['/app/entrypoint.sh']
    restart: unless-stopped
    network_mode: bridge
    init: true
    stop_grace_period: 90s
